version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
#    image: botservice:local
    container_name: BOT_WEB
    ports:
      - "8000:8000"
    volumes:
      - /opt/findface-multi/data/findface-multi-legacy/uploads:/img
#      - C:\Users\nikolay.korchik\Downloads\:/img
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
