version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
#    image: botservice:local
    container_name: BOT_WEB
    ports:
      - "8000:8000"
    volumes:
      - /uploads:/img
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
