version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: BOT
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - /opt/findface-multi/data/findface-multi-legacy/uploads:/img
#      - C:\Users\nikolay.korchik\Downloads\:/img
